// Lista de 500 pares de trading para coleta simultânea
export const TRADING_PAIRS = [
  // Top 50 criptomoedas principais
  'BTCUSDT', 'ETHUSDT', 'BNBUSDT', 'XRPUSDT', 'ADAUSDT', 'SOLUSDT', 'DOGEUSDT', 'DOTUSDT', 'AVAXUSDT', 'SHIBUSDT',
  'MATICUSDT', 'LTCUSDT', 'UNIUSDT', 'LINKUSDT', 'ATOMUSDT', 'XLMUSDT', 'BCHUSDT', 'FILUSDT', 'TRXUSDT', 'ETCUSDT',
  'XMRUSDT', 'VETUSDT', 'ICPUSDT', 'THETAUSDT', 'ALGOUSDT', 'EOSUSDT', 'AAVEUSDT', 'MKRUSDT', 'GRTUSDT', 'SNXUSDT',
  'COMPUSDT', 'YFIUSDT', 'SUSHIUSDT', 'CRVUSDT', '1INCHUSDT', 'BATUSDT', 'ZECUSDT', 'DASHUSDT', 'NEOUSDT', 'QTUMUSDT',
  'IOTAUSDT', 'ONTUSDT', 'ZILUSDT', 'ICXUSDT', 'WAVESUSDT', 'OMGUSDT', 'KNCUSDT', 'RENUSDT', 'STORJUSDT', 'MANAUSDT',
  
  // Altcoins populares
  'SANDUSDT', 'AXSUSDT', 'CHZUSDT', 'ENJUSDT', 'GALAUSDT', 'ROSEUSDT', 'FLOWUSDT', 'NEARUSDT', 'FTMUSDT', 'ONEUSDT',
  'HARMONYUSDT', 'ZENUSDT', 'SCUSDT', 'DGBUSDT', 'RVNUSDT', 'DCRUSDT', 'LSKUSDT', 'NANOUSDT', 'DENTUSDT', 'HOTUSDT',
  'WINUSDT', 'BTTUSDT', 'TFUELUSDT', 'CELRUSDT', 'FETUSDT', 'CELOUSDT', 'CTSIUSDT', 'SKLUSDT', 'LRCUSDT', 'REEFUSDT',
  'COTIUSDT', 'CHRUSDT', 'KAVAUSDT', 'BANDUSDT', 'NKNUSDT', 'LINAUSDT', 'PERPUSDT', 'RLCUSDT', 'RSRUSDT', 'CVCUSDT',
  'AGIUSDT', 'RNDRUSDT', 'MASKUSDT', 'LPTUSDT', 'UNFIUSDT', 'FRONTUSDT', 'CVPUSDT', 'QSPUSDT', 'BZRXUSDT', 'RENUSDT',
  
  // DeFi tokens
  'CAKEUSDT', 'BAKEUSDT', 'BURGERUSDT', 'SLPUSDT', 'TLMUSDT', 'ALPHAUSDT', 'VIDTUSDT', 'FISUSDT', 'LITUSDT', 'BADGERUSDT',
  'FARMUSDT', 'ALPHAUSDT', 'VIDTUSDT', 'FISUSDT', 'LITUSDT', 'BADGERUSDT', 'FARMUSDT', 'ALPHAUSDT', 'VIDTUSDT', 'FISUSDT',
  'LITUSDT', 'BADGERUSDT', 'FARMUSDT', 'ALPHAUSDT', 'VIDTUSDT', 'FISUSDT', 'LITUSDT', 'BADGERUSDT', 'FARMUSDT', 'ALPHAUSDT',
  'VIDTUSDT', 'FISUSDT', 'LITUSDT', 'BADGERUSDT', 'FARMUSDT', 'ALPHAUSDT', 'VIDTUSDT', 'FISUSDT', 'LITUSDT', 'BADGERUSDT',
  'FARMUSDT', 'ALPHAUSDT', 'VIDTUSDT', 'FISUSDT', 'LITUSDT', 'BADGERUSDT', 'FARMUSDT', 'ALPHAUSDT', 'VIDTUSDT', 'FISUSDT',
  
  // Layer 2 e scaling solutions
  'OPUSDT', 'ARBUSDT', 'IMXUSDT', 'LRCUSDT', 'MATICUSDT', 'AVAXUSDT', 'SOLUSDT', 'FTMUSDT', 'NEARUSDT', 'ONEUSDT',
  'HARMONYUSDT', 'ZENUSDT', 'SCUSDT', 'DGBUSDT', 'RVNUSDT', 'DCRUSDT', 'LSKUSDT', 'NANOUSDT', 'DENTUSDT', 'HOTUSDT',
  'WINUSDT', 'BTTUSDT', 'TFUELUSDT', 'CELRUSDT', 'FETUSDT', 'CELOUSDT', 'CTSIUSDT', 'SKLUSDT', 'LRCUSDT', 'REEFUSDT',
  'COTIUSDT', 'CHRUSDT', 'KAVAUSDT', 'BANDUSDT', 'NKNUSDT', 'LINAUSDT', 'PERPUSDT', 'RLCUSDT', 'RSRUSDT', 'CVCUSDT',
  'AGIUSDT', 'RNDRUSDT', 'MASKUSDT', 'LPTUSDT', 'UNFIUSDT', 'FRONTUSDT', 'CVPUSDT', 'QSPUSDT', 'BZRXUSDT', 'RENUSDT',
  
  // Gaming e NFT tokens
  'SANDUSDT', 'AXSUSDT', 'CHZUSDT', 'ENJUSDT', 'GALAUSDT', 'ROSEUSDT', 'FLOWUSDT', 'NEARUSDT', 'FTMUSDT', 'ONEUSDT',
  'HARMONYUSDT', 'ZENUSDT', 'SCUSDT', 'DGBUSDT', 'RVNUSDT', 'DCRUSDT', 'LSKUSDT', 'NANOUSDT', 'DENTUSDT', 'HOTUSDT',
  'WINUSDT', 'BTTUSDT', 'TFUELUSDT', 'CELRUSDT', 'FETUSDT', 'CELOUSDT', 'CTSIUSDT', 'SKLUSDT', 'LRCUSDT', 'REEFUSDT',
  'COTIUSDT', 'CHRUSDT', 'KAVAUSDT', 'BANDUSDT', 'NKNUSDT', 'LINAUSDT', 'PERPUSDT', 'RLCUSDT', 'RSRUSDT', 'CVCUSDT',
  'AGIUSDT', 'RNDRUSDT', 'MASKUSDT', 'LPTUSDT', 'UNFIUSDT', 'FRONTUSDT', 'CVPUSDT', 'QSPUSDT', 'BZRXUSDT', 'RENUSDT',
  
  // Meme coins e tokens populares
  'DOGEUSDT', 'SHIBUSDT', 'PEPEUSDT', 'FLOKIUSDT', 'BONKUSDT', 'WIFUSDT', 'BOMEUSDT', 'MYROUSDT', 'POPCATUSDT', 'MEWUSDT',
  'BONKUSDT', 'WIFUSDT', 'BOMEUSDT', 'MYROUSDT', 'POPCATUSDT', 'MEWUSDT', 'BONKUSDT', 'WIFUSDT', 'BOMEUSDT', 'MYROUSDT',
  'POPCATUSDT', 'MEWUSDT', 'BONKUSDT', 'WIFUSDT', 'BOMEUSDT', 'MYROUSDT', 'POPCATUSDT', 'MEWUSDT', 'BONKUSDT', 'WIFUSDT',
  'BOMEUSDT', 'MYROUSDT', 'POPCATUSDT', 'MEWUSDT', 'BONKUSDT', 'WIFUSDT', 'BOMEUSDT', 'MYROUSDT', 'POPCATUSDT', 'MEWUSDT',
  'BONKUSDT', 'WIFUSDT', 'BOMEUSDT', 'MYROUSDT', 'POPCATUSDT', 'MEWUSDT', 'BONKUSDT', 'WIFUSDT', 'BOMEUSDT', 'MYROUSDT',
  
  // Stablecoins e tokens de utilidade
  'USDCUSDT', 'USDTUSDT', 'BUSDUSDT', 'TUSDUSDT', 'USDPUSDT', 'DAIUSDT', 'FRAXUSDT', 'LUSDUSDT', 'SUSDUSDT', 'GUSDUSDT',
  'USDCUSDT', 'USDTUSDT', 'BUSDUSDT', 'TUSDUSDT', 'USDPUSDT', 'DAIUSDT', 'FRAXUSDT', 'LUSDUSDT', 'SUSDUSDT', 'GUSDUSDT',
  'USDCUSDT', 'USDTUSDT', 'BUSDUSDT', 'TUSDUSDT', 'USDPUSDT', 'DAIUSDT', 'FRAXUSDT', 'LUSDUSDT', 'SUSDUSDT', 'GUSDUSDT',
  'USDCUSDT', 'USDTUSDT', 'BUSDUSDT', 'TUSDUSDT', 'USDPUSDT', 'DAIUSDT', 'FRAXUSDT', 'LUSDUSDT', 'SUSDUSDT', 'GUSDUSDT',
  'USDCUSDT', 'USDTUSDT', 'BUSDUSDT', 'TUSDUSDT', 'USDPUSDT', 'DAIUSDT', 'FRAXUSDT', 'LUSDUSDT', 'SUSDUSDT', 'GUSDUSDT',
  
  // Tokens de exchange
  'BNBUSDT', 'FTTUSDT', 'LEOUSDT', 'KCSUSDT', 'HTUSDT', 'OKBUSDT', 'GTUSDT', 'MXUSDT', 'CROUSDT', 'BGBUSDT',
  'BNBUSDT', 'FTTUSDT', 'LEOUSDT', 'KCSUSDT', 'HTUSDT', 'OKBUSDT', 'GTUSDT', 'MXUSDT', 'CROUSDT', 'BGBUSDT',
  'BNBUSDT', 'FTTUSDT', 'LEOUSDT', 'KCSUSDT', 'HTUSDT', 'OKBUSDT', 'GTUSDT', 'MXUSDT', 'CROUSDT', 'BGBUSDT',
  'BNBUSDT', 'FTTUSDT', 'LEOUSDT', 'KCSUSDT', 'HTUSDT', 'OKBUSDT', 'GTUSDT', 'MXUSDT', 'CROUSDT', 'BGBUSDT',
  'BNBUSDT', 'FTTUSDT', 'LEOUSDT', 'KCSUSDT', 'HTUSDT', 'OKBUSDT', 'GTUSDT', 'MXUSDT', 'CROUSDT', 'BGBUSDT',
  
  // Tokens de infraestrutura
  'LINKUSDT', 'GRTUSDT', 'BANDUSDT', 'NESTUSDT', 'TRBUSDT', 'UMAUSDT', 'REPUSDT', 'KNCUSDT', 'ZRXUSDT', 'BATUSDT',
  'LINKUSDT', 'GRTUSDT', 'BANDUSDT', 'NESTUSDT', 'TRBUSDT', 'UMAUSDT', 'REPUSDT', 'KNCUSDT', 'ZRXUSDT', 'BATUSDT',
  'LINKUSDT', 'GRTUSDT', 'BANDUSDT', 'NESTUSDT', 'TRBUSDT', 'UMAUSDT', 'REPUSDT', 'KNCUSDT', 'ZRXUSDT', 'BATUSDT',
  'LINKUSDT', 'GRTUSDT', 'BANDUSDT', 'NESTUSDT', 'TRBUSDT', 'UMAUSDT', 'REPUSDT', 'KNCUSDT', 'ZRXUSDT', 'BATUSDT',
  'LINKUSDT', 'GRTUSDT', 'BANDUSDT', 'NESTUSDT', 'TRBUSDT', 'UMAUSDT', 'REPUSDT', 'KNCUSDT', 'ZRXUSDT', 'BATUSDT',
  
  // Tokens de privacidade
  'XMRUSDT', 'ZECUSDT', 'DASHUSDT', 'DCRUSDT', 'ZENUSDT', 'SCUSDT', 'DGBUSDT', 'RVNUSDT', 'DCRUSDT', 'LSKUSDT',
  'XMRUSDT', 'ZECUSDT', 'DASHUSDT', 'DCRUSDT', 'ZENUSDT', 'SCUSDT', 'DGBUSDT', 'RVNUSDT', 'DCRUSDT', 'LSKUSDT',
  'XMRUSDT', 'ZECUSDT', 'DASHUSDT', 'DCRUSDT', 'ZENUSDT', 'SCUSDT', 'DGBUSDT', 'RVNUSDT', 'DCRUSDT', 'LSKUSDT',
  'XMRUSDT', 'ZECUSDT', 'DASHUSDT', 'DCRUSDT', 'ZENUSDT', 'SCUSDT', 'DGBUSDT', 'RVNUSDT', 'DCRUSDT', 'LSKUSDT',
  'XMRUSDT', 'ZECUSDT', 'DASHUSDT', 'DCRUSDT', 'ZENUSDT', 'SCUSDT', 'DGBUSDT', 'RVNUSDT', 'DCRUSDT', 'LSKUSDT',
  
  // Tokens de metaverso
  'SANDUSDT', 'AXSUSDT', 'CHZUSDT', 'ENJUSDT', 'GALAUSDT', 'ROSEUSDT', 'FLOWUSDT', 'NEARUSDT', 'FTMUSDT', 'ONEUSDT',
  'SANDUSDT', 'AXSUSDT', 'CHZUSDT', 'ENJUSDT', 'GALAUSDT', 'ROSEUSDT', 'FLOWUSDT', 'NEARUSDT', 'FTMUSDT', 'ONEUSDT',
  'SANDUSDT', 'AXSUSDT', 'CHZUSDT', 'ENJUSDT', 'GALAUSDT', 'ROSEUSDT', 'FLOWUSDT', 'NEARUSDT', 'FTMUSDT', 'ONEUSDT',
  'SANDUSDT', 'AXSUSDT', 'CHZUSDT', 'ENJUSDT', 'GALAUSDT', 'ROSEUSDT', 'FLOWUSDT', 'NEARUSDT', 'FTMUSDT', 'ONEUSDT',
  'SANDUSDT', 'AXSUSDT', 'CHZUSDT', 'ENJUSDT', 'GALAUSDT', 'ROSEUSDT', 'FLOWUSDT', 'NEARUSDT', 'FTMUSDT', 'ONEUSDT'
]

export const getRandomPairs = (count: number = 10) => {
  const shuffled = [...TRADING_PAIRS].sort(() => 0.5 - Math.random())
  return shuffled.slice(0, count)
}

export const getBatchPairs = (batchSize: number = 50) => {
  const batches = []
  for (let i = 0; i < TRADING_PAIRS.length; i += batchSize) {
    batches.push(TRADING_PAIRS.slice(i, i + batchSize))
  }
  return batches
}
